version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 service_name

services:

  mongo:
    # Hardcoding to 4.4 as latest versions tend to cause issues with some CPUs
    image: mongo:4.4
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: SpyderC2
    volumes:
      - ./001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - ./db:/data/db
    command: ['--logpath', '/dev/null']
      

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mongo
    volumes:
      - ./data/shared/tmp:/home/attacker/SpyderC2/shared/tmp
      - ./data/shared/victim_data:/home/attacker/SpyderC2/shared/victim_data
      ## The below mounts are for android apk gen, so that we don't need to recompile everything from scratch everytime
      - ./data/shared/buildozer_docker/.buildozer_cwd:/home/attacker/SpyderC2/shared/.buildozer
      - ./data/shared/buildozer_docker/.buildozer_home:/root/.buildozer
    environment:
      MONGODB_DATABASE: SpyderC2
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongo
    ports:
      - 8080-8100:8080-8100
    healthcheck:
        test: ["CMD", "echo", "Server Started"]
        interval: 1s
        timeout: 1s
        retries: 5
