version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 service_name

services:

  mongo:
    image: mongo
    restart: always
    container_name: spyderc2_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: SpyderC2
    volumes:
      - ./001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
    command: ['--logpath', '/dev/null']
    # volumes:
    #   - ./mongo:/docker-entrypoint-initdb.d

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spyderc2_server
    depends_on:
      - mongo
    volumes:
      - ./data/shared:/home/attacker/SpyderC2/shared
    environment:
      MONGODB_DATABASE: SpyderC2
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongo
    ports:
      - "8080:8080"
    healthcheck:
        test: ["CMD", "echo", "Server Started"]
        interval: 1s
        timeout: 1s
        retries: 5